namespace WinEvents
{
	using System.Runtime.InteropServices;

	internal partial class NativeMethods
	{
		/// <summary>
		/// Contains information about a simulated message generated by an input device other than a keyboard or mouse.
		/// </summary>
		[StructLayout(LayoutKind.Sequential)]
		public struct HardwareInput
		{
			public uint message;
			public ushort wParamL;
			public ushort wParamH;
		}
	}
}
